# Generated by Django 4.2.29 on 2026-07-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_amount_alter_invoice_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={},
        ),
        migrations.AddField(
            model_name='invoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='unit',
            field=models.CharField(default='Adet', max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(default='TL', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_country',
            field=models.CharField(blank=True, default='Türkiye', max_length=100),
        ),
    ]
