# Generated by Django 4.2.29 on 2026-07-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_category_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('sent', 'Gönderildi'), ('approved', 'Onaylandı'), ('paid', 'Ödendi'), ('cancelled', 'İptal'), ('rejected', 'Reddedildi'), ('returned', 'İade')], default='draft', max_length=20),
        ),
    ]
