# Generated by Django 4.2.29 on 2026-07-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='customer_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_country',
            field=models.CharField(blank=True, default='Türkiye', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='delivery_street',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
