# Generated by Django 4.2.29 on 2026-07-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_optional_fields_44_54'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='export_customs_tracking_no',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gümrük Takip No'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_building_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teslim Yeri - Bina Adı'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_building_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teslim Yeri - Bina No'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teslim Yeri - Şehir'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teslim Yeri - Ülke'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_district',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teslim Yeri - İlçe'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_door_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teslim Yeri - Kapı No'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teslim Yeri - Posta Kodu'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_street',
            field=models.CharField(blank=True, max_length=200, verbose_name='Teslim Yeri - Cadde/Sokak'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_terms',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teslim Şartı'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_delivery_town',
            field=models.CharField(blank=True, max_length=100, verbose_name='Teslim Yeri - Kasaba/Köy'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_gtip_no',
            field=models.CharField(blank=True, max_length=50, verbose_name='GTİP No'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_package_count',
            field=models.CharField(blank=True, max_length=20, verbose_name='Kap Adedi'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_package_marks',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kabın Markası/Cinsi'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_package_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Kap Numarası'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='export_shipping_method',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gönderilme Şekli'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='additional_description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Açıklama (Ek)'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='additional_info_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ek Bilgi ID'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, verbose_name='Üretici Kodu / Barkod'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='brand',
            field=models.CharField(blank=True, max_length=150, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='buyer_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alıcı Kodu'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='classification_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sınıflandırma Kodu'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='classification_value',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sınıflandırma Değeri'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='classification_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Sınıflandırma Versiyonu'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='item_note',
            field=models.CharField(blank=True, max_length=500, verbose_name='Not'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Sipariş Tarihi'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sipariş No'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='origin_country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Menşei'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='related_waybill_date',
            field=models.DateField(blank=True, null=True, verbose_name='İrsaliye Tarihi'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='related_waybill_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='İrsaliye No'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='seller_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Satıcı Kodu'),
        ),
    ]
