# Generated by Django 6.0.3 on 2026-03-05 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Check",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("received", "Alınan Çek"), ("issued", "Verilen Çek")],
                        max_length=20,
                    ),
                ),
                ("check_number", models.CharField(max_length=50)),
                ("bank_name", models.CharField(max_length=200)),
                ("branch", models.CharField(blank=True, max_length=200)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("payer_name", models.CharField(max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("portfolio", "Portföyde"),
                            ("banked", "Bankaya Verildi"),
                            ("cashed", "Tahsil Edildi"),
                            ("returned", "İade"),
                            ("cancelled", "İptal"),
                        ],
                        default="portfolio",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Çek",
                "verbose_name_plural": "Çekler",
                "db_table": "checks",
                "ordering": ["-due_date"],
            },
        ),
        migrations.CreateModel(
            name="Promissory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("received", "Alınan Senet"),
                            ("issued", "Verilen Senet"),
                        ],
                        max_length=20,
                    ),
                ),
                ("promissory_number", models.CharField(max_length=50)),
                ("drawer_name", models.CharField(max_length=200)),
                ("endorser_name", models.CharField(blank=True, max_length=200)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField()),
                ("place_of_issue", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("portfolio", "Portföyde"),
                            ("banked", "Bankaya Verildi"),
                            ("cashed", "Tahsil Edildi"),
                            ("returned", "İade"),
                            ("cancelled", "İptal"),
                        ],
                        default="portfolio",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promissories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Senet",
                "verbose_name_plural": "Senetler",
                "db_table": "promissories",
                "ordering": ["-due_date"],
            },
        ),
    ]
